import { db } from "@/lib/firebase/config";
import { collection, getDocs } from "firebase/firestore";
import { NextResponse } from "next/server";

/*
 * Get all the chats for a given user
 * Params:
 *  None
 * Request body:
 *  user_id: global id of a User
 *  first: first name
 *  last: last name,
 *  email_address: email address
 * Return:
 *  data: id of the new User generated by firestore
 *  error: error or null
 */
export async function GET() {
  let result = null;
  let error = null;

  try {
    result = await getDocs(collection(db, "chats"));
    // convert the firebase response object
    result = result.docs.map((doc) => ({
      ...doc.data(),
      id: doc.id,
    }));
  } catch (err) {
    error = err;
  }

  return NextResponse.json({ result, error });
}
